### ISSUE TITLE
pyo install issue on Mac M1

### ISSUE THREAD

**Issue by vlzhr** [kiecodes/generate-music#1]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/22869641/167718463-c93c78d9-907b-4435-b7ae-ffed194ab875.png">

getting this while running 'pip3 install -r requirements.txt'

**Comment by antiero** [comment]
Also getting errors on an Intel Mac, macOS Monterey. I'm interested to know which versions of macOS you got this working on @thekie ? Really keen to give it a try!

**Comment by Banthex** [comment]
Maybe not the same but on archi linux i had to install "python3-pyo" first.

**Comment by joniuz** [comment]
I had the same errors about files that don't exist in my Mac such us

include/ad_portaudio.h:25:10: fatal error: 'portaudio.h' file not found

include/servermodule.h:31:10: fatal error: 'sndfile.h' file not found

include/md_portmidi.h:25:10: fatal error: 'portmidi.h' file not found

src/engine/osclistenermodule.c:26:10: fatal error: 'lo/lo.h' file not found

I solved the errors by installing several libraries using brew

Joniuz-MacBook-Air:generate-music joniuz$ brew install portaudio

Joniuz-MacBook-Air:generate-music joniuz$ brew install libsndfile

Joniuz-MacBook-Air:generate-music joniuz$ brew install portmidi

Joniuz-MacBook-Air:generate-music joniuz$ brew install liblo

But I couldn't solve the last one, it shows an incompatible function pointer type:

      src/engine/osclistenermodule.c:165:56: error: incompatible function pointer types passing 'int (const char *, const char *, lo_arg **, int, void *, void *)' to parameter of type 'lo_method_handler' (aka 'int (*)(const char *, const char *, lo_arg **, int, struct lo_message_ *, void *)') [-Wincompatible-function-pointer-types]
        165 |     lo_server_add_method(self->osc_server, NULL, NULL, process_osc, (void *)self);
            |                                                        ^~~~~~~~~~~
      /usr/local/include/lo/lo_lowlevel.h:876:72: note: passing argument to parameter 'h' here
        876 |                                const char *typespec, lo_method_handler h,
            |                                                                        ^
      3 warnings and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1

Do you have any idea what the pyo library is for?

**Comment by joniuz** [comment]
I got the pyo installation working on python 3.9 but still didn't work in my Mac, then I modified the program to work with the Mido library and send midi messages to my Korg Volca FM. 

I added more scales and made the user interface a more friendly.

Check my updates in https://github.com/joniuz/generate-music
